name: Reusable Workflows
on:
  workflow_call: # Reusable Workflowsを起動するイベント
    inputs:
      pr-number:
        type: string
        default: ${{ github.event.pull_request.number }}
        required: false
        description: Pull Request Number
    secrets:
      token:
        required: true
        description: GitHub Token
    outputs:
      message:
        value: ${{ jobs.comment.outputs.pr-comment }}
        description: Comment message

jobs:
  comment:
    name: Comment on Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - id: pr-comment
        run: |
          body="Welcome, ${GITHUB_ACTOR}!"
          gh pr comment "${PR_NUMBER}" --body "${body}"
          echo "body=${body}" >> "${GITHUB_OUTPUT}"
        env:
          PR_NUMBER: ${{ inputs.pr-number }}
          GITHUB_TOKEN: ${{ secrets.token }}
    outputs:
      pr-comment: ${{ steps.pr-comment.outputs.body }}